version: 0.1
phases:
  build:
    commands:
      - echo "hello, hell"
      - pip install git+ssh://git@github.com/cgauge/mailexpress-utils.git@settings-refactoring#egg=cgmailexpressutils

artifacts:
  type: zip
  files:
    - program.py
