version: 0.1

phases:
  build:
    commands:
      - env
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --build-arg GITHUB_DEPLOY_TOKEN=$GITHUB_DEPLOY_TOKEN  .
      #- docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
