version: 0.1

phases:
#  pre_build:
#    commands:
  build:
    commands:
      # that's what really normally goes into pre_build
      - echo Logging in to Amazon ECR...
      - aws ecr get-login --region $AWS_DEFAULT_REGION
      - date +%y.%j_%H.%M > _tag
      - env
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --build-arg GITHUB_DEPLOY_TOKEN=$GITHUB_DEPLOY_TOKEN  .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$(cat _tag)
  post_build:
    commands:
      - echo "Build of $IMAGE_REPO_NAME:$(cat _tag) completed on `date`"
      - echo "Pushing the Docker image..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$(cat _tag)
      - echo "Generating change set"
      - aws cloudformation create-change-set --stack-name codepipeline-demo --change-set-name UpdateService --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue=$(cat _tag) --change-set-type UPDATE
      - sleep 120
      - aws cloudformation execute-change-set --stack-name codepipeline-demo --change-set-name UpdateService
artifacts:
  files:
    - "_tag"
