version: 0.1
phases:
  build:
    commands:
      - echo "hello, hell"
      - pip install -U pip
      - echo "_____________"
      - env
      - echo "^^^^^^^^^^^^^"

artifacts:
  type: zip
  files:
    - program.py
