version: 0.1
phases:
  build:
    commands:
      - echo "hello, hell"
      - pip install git+https://github.com/cgauge/mailexpress-utils.git#egg=cgmailexpressutils

artifacts:
  type: zip
  files:
    - program.py
